// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDefaultDNS() {
  return window['go']['main']['App']['GetDefaultDNS']();
}

export function GetNetworkAdapters() {
  return window['go']['main']['App']['GetNetworkAdapters']();
}
