// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomDNSServer(arg1, arg2) {
  return window['go']['main']['App']['AddCustomDNSServer'](arg1, arg2);
}

export function ApplyDNS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ApplyDNS'](arg1, arg2, arg3, arg4);
}

export function BackupCurrentDNS(arg1) {
  return window['go']['main']['App']['BackupCurrentDNS'](arg1);
}

export function CreateCustomDNSList(arg1, arg2) {
  return window['go']['main']['App']['CreateCustomDNSList'](arg1, arg2);
}

export function DeleteCustomDNSList(arg1) {
  return window['go']['main']['App']['DeleteCustomDNSList'](arg1);
}

export function DeleteCustomDNSServer(arg1) {
  return window['go']['main']['App']['DeleteCustomDNSServer'](arg1);
}

export function FindFastestDNS(arg1) {
  return window['go']['main']['App']['FindFastestDNS'](arg1);
}

export function FlushDNSCache() {
  return window['go']['main']['App']['FlushDNSCache']();
}

export function GetBenchmarkProfiles() {
  return window['go']['main']['App']['GetBenchmarkProfiles']();
}

export function GetCustomDNSLists() {
  return window['go']['main']['App']['GetCustomDNSLists']();
}

export function GetDefaultDNS() {
  return window['go']['main']['App']['GetDefaultDNS']();
}

export function GetNetworkAdapters() {
  return window['go']['main']['App']['GetNetworkAdapters']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSystemDNS() {
  return window['go']['main']['App']['GetSystemDNS']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RunBenchmark(arg1, arg2) {
  return window['go']['main']['App']['RunBenchmark'](arg1, arg2);
}

export function SaveCustomDNSList(arg1) {
  return window['go']['main']['App']['SaveCustomDNSList'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
