// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetDefaultDNS():Promise<Array<models.DNSServer>>;

export function GetNetworkAdapters():Promise<Array<models.NetworkAdapter>>;
