// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {benchmark} from '../models';

export function AddCustomDNSServer(arg1:string,arg2:models.DNSServer):Promise<void>;

export function ApplyDNS(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function BackupCurrentDNS(arg1:string):Promise<void>;

export function CreateCustomDNSList(arg1:string,arg2:string):Promise<string>;

export function DeleteCustomDNSList(arg1:string):Promise<void>;

export function DeleteCustomDNSServer(arg1:string):Promise<void>;

export function FindFastestDNS(arg1:Array<string>):Promise<Array<benchmark.Result>>;

export function FlushDNSCache():Promise<void>;

export function GetBenchmarkProfiles():Promise<Array<models.BenchmarkProfile>>;

export function GetCustomDNSLists():Promise<Array<models.CustomDNSList>>;

export function GetDefaultDNS():Promise<Array<models.DNSServer>>;

export function GetNetworkAdapters():Promise<Array<models.NetworkAdapter>>;

export function GetSettings():Promise<models.Settings>;

export function GetSystemDNS():Promise<Array<models.DNSInfo>>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RunBenchmark(arg1:string,arg2:Array<string>):Promise<Array<models.BenchmarkResult>>;

export function SaveCustomDNSList(arg1:models.CustomDNSList):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;
